#pull a base image which gives all required tools and libraries
FROM python:3.9

#create a folder where the app code will be stored
WORKDIR /app

#Copy the source code from your Host Machine to your container
COPY app.py .

#compile the application code
#RUN command

#run the application
CMD ["python","app.py"]
